Fix get_from_tests run_command_in_container call
- The issue_gen.get_from_tests command was updated in cabec5da to read
  the test command timeout from the repo profile
- However the caller was not updated to pass the repo profile through

Fixes:

```
TypeError: run_command_in_container() missing 1 required positional argument: 'rp'
```