Drop unsupported model params
- Attempts to use gpt-5 models with certain commands would fail
  previously due to temperature not being supported
- Set litellm.drop_params to drop parameters not supported by models

Fixes:

litellm.exceptions.UnsupportedParamsError: litellm.UnsupportedParamsError: gpt-5 models don't support temperature=0. Only temperature=1 is supported. To drop unsupported params set `litellm.drop_params = True`